on:
  push:
    branches:
      - main
  
jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 
      - name: Deploy in EC2
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY  }}
        run: |
         echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
         ssh -o StrictHostKeyChecking=no -i private_key root@89.116.33.124 'cd /var/www/hdms-backend && git pull https://jawad-shaikh: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@github.com/jawad-shaikh/HDMS-backend.git && npm i'
